/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for WORKBEN.HH
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new context strings that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for context strings
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define IDH_CONTENTS 0
#define Event_Log_Contents 1
#define Claim_Search_Contents 2
#define How_Do_I_Search_For_A_Claim 3
#define To_perform_a_Claim_Number_search 4
#define Note1_For_All_Searches 5
#define To_perform_a_Basic_Claim_search 6
#define Note2_For_All_Searches 7
#define To_search_by_Case_Load 8
#define Search_Screen 10
#define How_Do_I_Print_My_Search_Results 11
#define How_Do_I_View_Documents 12
#define How_Do_I_Print_Documents 13
#define How_Do_I_Import_Documents 14
#define Event_Log 15
#define How_Do_I_Add_A_Manual_Event 16
#define New_Event_Log_Screen 17
#define How_Do_I_Filter_Sort_and_Get_More_Details 18
#define Sort 19
#define Filter 20
#define More_Details 21
#define More_Details_Screen 22
#define How_Do_I_Print_the_Event_Log 23
#define How_Do_I_Retrieve_A_Claim 24
#define Note_3_For_All_Searches 26
#define To_Perform_a_Due_Overdue_search 27
#define How_Do_I_View_All_the_Comments_at_One_Time 28
#define How_Do_I_Request_a_Medical_Opinion 29
#define How_Do_I_Respond_to_a_Medical_Opinion_Request 30
#define How_Do_I_Respond_to_a_Medical_Opinion_Request 30
#define How_Do_I_Change_The_Status_of_a_Claim 32
#define Active 33
#define How_Do_I_Assign_a_Claim_Manager 34
#define How_Do_I_Add_an_Opening_Occurrence 35
#define Claim_Disposition_Codes_for_Openings 36
#define Valid_Code_Combinations_for_Openings 37
#define How_Do_I_Add_a_Claim_Participant 38
#define Claim_Role_Individual_Maintenance_Screen 39
#define How_Do_I_View_Participant_Information 40
#define How_Do_I_Add_An_Employer_to_a_Claim 41
#define How_Do_I_Update_the_Individual 43
#define Maintain_Individual 44
#define Claim_Status_and_Events_Chart 45
#define Claim_Maintenance 47
#define Logging_of_Non_Imaged_Claim_Files_and_Correspondence 48
#define How_Do_I_Log_Files_In_Out 49
#define How_Do_I_Log_In_a_File 50
#define How_Do_I_Print_The_Log 51
#define How_Do_I_Sort_The_Log 52
#define How_Do_I_Maintain_Correspondence_For_Non_Imaged_Claims 53
#define How_Do_I_Change_an_Existing_Entry 54
#define How_Do_I_Delete_an_Entry 55
#define How_Do_I_Print_and_Sort_the_Correspondence_Log 56
#define Indexing 57
#define How_Do_I_Index_a_Document 58
#define Claim_Create 59
#define Account_Payments 60
#define How_Do_I_Search_For_Service_Provider_Numbers 62
#define How_Do_I_Create_a_Claim 63
#define What_s_the_Override_Button 64
#define How_Do_I_Schedule_Accounts_for_Payment 65
#define Account_Payment_Screen 66
#define How_Do_I_Reject_Accounts 67
#define How_Do_I_Delete_a_Scheduled_Payment 68
#define How_Do_I_Remove_an_Account_From_My_Bucket 69
#define How_Do_I_Print_The_Contents_of_My_Bucket 70
#define How_Do_I_Sort_The_Contents_of_My_Bucket 71
#define How_Do_I_Filter_The_Contents_of_My_Bucket 72
#define How_Do_I_Search_For_a_Claim_in_Indexing 73
#define How_Do_I_Send_Documents_to_a_Person_s_InBasket 74
#define What_Does_The_Link_Button_Do 75
#define How_Do_I_Send_a_Linked_Document 76
#define How_Do_I_Issue_Advances 77
#define How_Do_I_Authorize_Account_Payments 79
#define How_Do_I_UnAuthorize_Payments 80
#define Service_Providers 81
#define How_Do_I_Change_Existing_Information 82
#define How_Do_I_Add_a_New_Provider 83
#define How_Do_I_Search_For_a_Provider 84
#define How_Do_I_get_a_Report_of_the_In_Out_Logging 85
#define WRC_Accommodations 86
#define In_Baskets 87
#define How_Do_I_Open_My_In_Basket 88
#define How_Do_I_Filter_Print_and_Sort_the_In_Basket 89
#define How_Do_I_Open_a_Folder 90
#define How_Do_I_Delete_an_Entire_Folder 91
#define How_Do_I_Forward_a_Folder 92
#define How_Do_I_Maintain_In_Out_Baskets 93
#define Correspondence 94
#define How_Do_I_Compose_a_Document 95
#define How_Do_I_Send_The_Document 96
#define How_Do_I_Delete_a_Document 97
#define How_Do_I_Edit_a_Document 98
#define How_Do_I_Add_to_the_Recipients_List 99
#define How_Do_I_Delete_a_Recipient 100
#define How_Do_I_Make_a_Provider_Inactive 101
#define Benefit_Calculation 102
#define How_Do_I_Create_a_Benefit_Calculation_for_Active_Claims 103
#define How_Do_I_Create_a_Benefit_Calculation_for_Adjudicated_Claims 104
#define How_Do_I_Copy_A_Benefit_Calculation 105
#define How_Do_I_Copy_a_Cost_Analysis_Calculation 106
#define How_Do_I_Delete_a_Benefit_Calculation 107
#define Payments 108
#define How_Do_I_Issue_a_Comp_Payment 109
#define How_Do_I_Split_a_Payment 110
#define How_Do_I_Issue_Weekly_Allowances 111
#define How_Do_I_Make_a_PPI_Payment 112
#define How_Do_I_View_What_Has_Been_Paid_to_a_Claimant 113
#define How_Do_I_Print_and_Filter_the_Payment_Inquiry 114
#define How_Do_I_View_More_Payment_Details 115
#define How_Do_I_Adjust_Cancel_Payments 116
#define How_Do_I_Cancel_Payments 117
#define How_Do_I_Re_Issue_a_Payment 118
#define How_Do_I_View_A_Re_Issue 119
#define How_Do_I_Final_a_Claim 120
#define How_Do_I_UnAuthorize_Account_Payments 121
#define How_Do_I_Authorize_Payments 122
#define How_Do_I_Run_the_Payment_Balancing_Report 123
#define How_Do_I_See_What_Payments_Were_Made 124
#define Document_Archiving 125
#define How_Do_I_Archive_a_Document 126
#define How_Do_I_Retrieve_an_Archived_Document 127
#define Accident_Statistics 128
#define How_Do_I_Search_for_Stats_Not_Coded 129
#define How_Do_I_Code_the_Accident_Statistics 130
#define Rehab 131
#define Cost_Analysis 132
#define How_Do_I_Open_a_Cost_Analysis 133
#define How_Do_I_Add_Options 134
#define How_Do_I_Delete_an_Option 135
#define How_Do_I_Print_the_Cost_Comparison 136
#define How_Do_I_Print_the_Summary_Report 137
#define How_Do_I_Select_the_Option_I_want_to_Recommend 138
#define Rehab_Plan 139
#define How_Do_I_Open_the_Rehab_Plan 140
#define How_Do_I_Add_a_Goal_Objective 141
#define To_add_a_Goal_Objective 142
#define How_Do_I_Add_a_Task 143
#define How_Do_I_Enter_Information_for_Authorization 144
#define How_Do_I_Add_a_Progress_Note 145
#define How_Do_I_Add_the_Vocational_Profile_Information 146
#define How_Do_I_Add_the_Case_Monitoring_Information 147
#define Awards 148
#define How_Do_I_Add_an_Award 149
#define How_Do_I_Add_a_Clothing_or_Care_Allowance_Award 150
#define Overpayments 151
#define How_to_Use_the_Overpayment_Module 152
#define How_Do_I_Enter_Advances 153
#define To_enter_the_Case_Monitoring_Information 154
#define How_Do_I_Pay_Accounts_With_Authorizations_from_the_Rehab_Plan 155
#define To_Do_List 156
#define How_Do_I_Print_the_Rehab_Plan 157
#define How_Do_I_Switch_between_the_To_Do_List_and_the_Rehab_Plan 158
#define How_Do_I_Filter_the_Plan 159
#define How_Do_I_Attach_a_Document_to_a_Progress_Note 160
#define How_Do_I_Print_the_Attachments 161
#define How_Do_I_View_the_Attachments 162
#define Reports 163
#define List_of_Task_Types_and_Subtypes 164
#define Document_Handling 165
#define How_Do_I_Sort_The_Plan 166
#define How_Do_I_View_The_Authorization_Information 167
